dist: trusty
language: csharp
mono: none
dotnet: 2.1.502  #3.1.300 # For some reason .Net Core v3.1 is not working with Travis. I might have been using the wrong version. Check cmd: dotnet --version
install:
- dotnet restore
addons:
  sonarcloud:
    organization: "markpthomas-github"
    token:
      # encrypted value of your token by running the command line: travis encrypt {token_provided_by_SonarCloud}
      secure:"dYcMRnnU0l+0wUY4BL7pPrs5Y0Ws0/ccKcKSaZYX+fnpnP6GNVcOG9V8HkH3e3UrUrP3QgrZry3JgL4cCiX+FO3dB2xuaMVyqj6ybva8PwV8xoLJvk5l09N3TCE4saYOFKPmqyNb7XzM2zTMAFSESnTiwtuYr8q+/5OJKv5GQVS0KmGXjqPVuJXNkeVMXz/LNU28AxhuWt7wX7mDFvIO4cLKzKZdEQ35g2PXTor6++qW2jxirySEZTyJzRbu363Ja5i9YH8taW/h7QUfKGRoPg2ck5lH+WU+5/J0hv3Klq8LhqpbUrWjODcKL9trEmlwbPdFJrtOoz03UtBQn4sMs56TAOwXZ3fVRrwpIxdCjklbCQuIvQuiQShL/TxEdK2RxqYnL6CNl0zf+0KRCyffGDG/jT6mv3eWUuwequa2sDrn5Y8Qjucnuw+vFjrbFdy/Hy5MJbvOfJKKnKMynBA7TtKUjiWTv0Lc6sih/YwyiqQFXRkvPwj3PmlhpbIgqylkpO64UBsBquvmh46tGWdA2rksu+HU8arhCL49+pPeCVgnBipPFzhuUjeQBi4abeLsZVg5IgNSQgzTwgToG7bg6ywmmSUaX/q7wUYeSeNrqrU+th83l/pWcZEz8NAUdLV0Tn93dsyOCq8l99UVZwL55UXwTmOiOwHn/ZNMAfsK05Q="

script:
  - dotnet build MPT.Math/MPT.Math.csproj
  - dotnet test MPT.Math.UnitTests/MPT.Math.UnitTests.csproj
  #- dotnet test MPT.Math.xUnitTests/MPT.Math.xUnitTests.csproj
  
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner