dist: trusty
language: csharp
mono: none
dotnet: 2.1.502  #3.1.300 # For some reason .Net Core v3.1 is not working with Travis. I might have been using the wrong version. Check cmd: dotnet --version
install:
- dotnet restore
addons:
  sonarcloud:
    organization: "markpthomas-github"
    token:
      # encrypted value of your token by running the command line: travis encrypt {token_provided_by_SonarCloud}
      secure:"uaxEDqCEqb0jY+KA1RL77iv2cIFu23F7UKr8Y+KtJMp4P8dtDwyKkHWFCEA68jxrpvCbbpkRNd7fFal/uoLxdKSjwbuyrQw3PPKjT+HoYOQwmGmZpxqCt3fjN9hTKIzGGXpCi0YXjG95FJQ+W5jYIXJdPvmfJnOdYeMNAYTtrOSG6ebCYBl6f9XLDr6AzKshkfRFeAytCr+IlcPPWJMHt3XsG7UiJAUUnfIH0RyuEbVGrVMz/NavdzGp+ZTgoWg8e8BfkLi2DnSRr+NB//bEXqJ553aiLV8F+WeMlK6BOSdy1a2Uh2C29nnpYbiC4wqNjL7tih1TNSmf1+DdA69IcTEY/dBMswJLyH+VH/CvhHK5GrdydtDQgeDLuvuYAT2gQaMJEn6n9s/F43hiVGIZp82FesaKjwyzA2bC6ib1Z7Vl9vlop5O6lwezI3wnhM8cSg4We58rZjjwF6rxszYE3d1AKoFPQDzBnNEuLHst3ZHvMWptEZX+7ZewKgj8mcDfH/hQvwqF7XlYfzGO84J+niaNItnTOXAEz1DSP9CN5KwYlbYYodszMMwWER2RxkIjccAkBK0c/jnu/HbrKK5WPsKiI6yr9XXnabIdA+XVVNs2RT2+pjoYGjCo2Pw7upPu9ljBCKP06yc5YFAfDPKvz2buzDqnaeMW76nr6ieQVKg="

script:
  - dotnet build MPT.Math/MPT.Math.csproj
  - dotnet test MPT.Math.UnitTests/MPT.Math.UnitTests.csproj
  #- dotnet test MPT.Math.xUnitTests/MPT.Math.xUnitTests.csproj
  
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner