dist: trusty
language: csharp
mono: none
#solution: MPT.Math.sln
dotnet: 3.1.201 #300
install:
  - dotnet restore
  
script:
  - dotnet build MPT.Math/MPT.Math.csproj -f netcoreapp3.1
  - dotnet test MPT.Math.UnitTests/MPT.Math.UnitTests.csproj -f netcoreapp3.1
