dist: trusty
language: csharp
mono: none
dotnet: 2.1.502  #3.1.300 # For some reason .Net Core v3.1 is not working with Travis. I might have been using the wrong version. Check cmd: dotnet --version
install:
- dotnet restore
addons:
  sonarcloud:
    organization: "markpthomas-github"
    token:
      # encrypted value of your token by running the command line: travis encrypt {token_provided_by_SonarCloud}
      secure:"mxUmP2RUBKXR0Tmp76pPVnEuUwUApradW4slwX2b/P55Mm6suYZCxok823bGflqNHSlO26YONGrrHvwDtrTVHoHeBZWZeOnKIUpuqnkmuvK0jno15pjKHw4zEDQCibUo7UA1cPG21l1kLb1OiCcxQb47p2Sd6CkZYj0d+dErIutA5rWWCigCgfoedTz5SEHQIDwn86nH5XVhFvxA4qgnPGn3RmEoAYMod1l+0zsEiKAbpYfUlFYo4oCE/R6/+3RPCqiMwm1LnzMCq4vD1TmcZiI+tPOixI4wAvrr4g8G54B1Kwn0qt/aP99jxtbXMpEOfhUNn/RfhhXkCThi4duGl6JePy6jaMfBBQOMiDLvmMFxlQSCHDwf8WRVcUWl+wpUB29EHVWP/5DJPGdmnh+jBPlwyYPjEcuQA5RJSDrBvrsZNGngtCjsV780M5YC9NYLArBb9ahMa3F26j8eZNszkIz2XdmKrU67aqLWMSSEtkyhQIbtlXGU1QagQz+JwV/fK8/3XzLm8BJPkC+CYP69T4giSgyit7ciFffHoobwXllNTZzcoHA65GGCoqgfNSc9ww+/D4XxJOqtsdXrE5IFOMZS/iD/1MyfdOC+TUVBvh01vo4Qrb7kIxuV/tp9UMJ6iDIsnb/vPH51mLZxWWu+MsKuRo91w8rQ+xac/3LV6nI="

script:
  - dotnet build MPT.Math/MPT.Math.csproj
  - dotnet test MPT.Math.UnitTests/MPT.Math.UnitTests.csproj
  #- dotnet test MPT.Math.xUnitTests/MPT.Math.xUnitTests.csproj
  
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner